/*
 * Created on 20 Jun 2017 ( Time 11:34:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.demo.service.impl;

import org.hibernate.Session;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

/**
 * 20140320
 * @param <T>
 */

public abstract class AbstractService<T> {
	
	@PersistenceContext
	EntityManager entityManager;

	private Class< T > clazz;

	public final void setClazz( Class< T > clazzToSet ){
	      this.clazz = clazzToSet;
	}
	 
	public final Session getSession() {
		return (Session) entityManager.unwrap(Session.class);
	}
}
